---
sidebar: sidebar
permalink: accesscache-reachedlimits-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: accesscache.reachedlimits events
---

= accesscache.reachedlimits events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== AccessCache.ReachedLimits
*Severity*::
EMERGENCY
*Description*::
This message occurs when the access cache module reaches its limit for entries. This condition can prevent new clients from being able to mount and perform I/O on the storage system. This condition can also cause clients to be granted or denied access based on stale information.
*Corrective Action*::
Ensure that the number of clients accessing the storage system is below the limits for access cache entries. If the set of clients accessing the storage system is constantly changing, consider using the "vserver export-policy access-cache config modify" command to reduce the harvest timeout parameter so that cache entries for clients that are no longer accessing the storage system can be evicted sooner.
*Syslog Message*::
The exports access cache module on this node reached its limit while trying to add %d new entries (current entries count : %u, entries limit : %u and current rules count : %u).
*Parameters*::
*numEntriesDelta* (INT): Number of new entries to be added.
*numEntriesCurrent* (INT): Current number of entries in the cache.
*numEntriesLimit* (INT): Limit on the number of entries.
*numRulesCurrent* (INT): Current number of export rules in the cache.
