---
sidebar: sidebar
permalink: api-input-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: api.input events
---

= api.input events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== api.input.invalidSchema
*Severity*::
ERROR
*Description*::
This message occurs when an ONTAPI(tm) API receives extra input parameters as part of the API request or when a required input parameter is missing in the API request. Most often this is due to a bug in the application that initiates the API request.
*Corrective Action*::
The error is due to strict schema validation. You can turn off the input schema validation by using the following CLI commands: $priv set advanced $registry set state.api.schema_input_validate.enable off
*Syslog Message*::
Error in API input schema validation. API name: %s. Detailed error: %s.
*Parameters*::
*apiName* (STRING): Name of the ONTAPI API in which something invalid was detected.
*detailInfo* (STRING): Description of the error in the API input, such as an extra input value or a missing input value.
