---
sidebar: sidebar
permalink: callhome-fdsk-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: callhome.fdsk events
---

= callhome.fdsk events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== callhome.fdsk.admin
*Severity*::
NOTICE
*Description*::
This message occurs when you fail a file system disk drive. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for FILESYSTEM DISK ADMIN FAILED
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.fault
*Severity*::
ERROR
*Description*::
This message occurs when a disk drive fails. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate the failed disk drive by looking for a disk drive whose red and amber LED fault lights are NOT lit. Replace the failed disk drive. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for %s
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.label
*Severity*::
ERROR
*Description*::
This message occurs when a disk drive fails due to unexpected RAID metadata. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate the failed disk drive by looking for a disk drive whose red and amber LED fault lights are NOT lit. Replace the failed disk drive. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for FILESYSTEM DISK BAD LABEL
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.label.v
*Severity*::
ERROR
*Description*::
This message occurs when a disk drive fails due to a version number in its RAID metadata that is inconsistent with the operating system version installed. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate the failed disk drive by looking for a disk drive whose red and amber LED fault lights are NOT lit. Replace the failed disk drive. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for FILESYSTEM DISK BAD LABEL VERSION
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.missing
*Severity*::
ERROR
*Description*::
This message occurs when the system detects that a disk drive is not in a loop or is missing. This might also occur when a failed disk drive is still in the chassis awaiting replacement. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate and replace the failed disk drive. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for FILESYSTEM DISK MISSING
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.noio
*Severity*::
ERROR
*Description*::
This message occurs when disk drive device commands to a file system disk drive are failing with link errors, adapter errors, or timeouts. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate the failed disk drive by looking for a disk drive whose red and amber LED fault lights are NOT lit. Replace the failed disk drive. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for FILESYSTEM DISK NOT RESPONDING
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.

== callhome.fdsk.shrank
*Severity*::
ERROR
*Description*::
This message occurs when an aggregate disk drive fails because its raw capacity was downsized due to a firmware change. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
Locate the failed disk drive by looking for a disk drive whose red and amber LED fault lights are NOT lit. Replace the failed disk drive. After the automated e-mail is sent to you with the case# and instructions, the case is closed. If you need assistance, contact NetApp technical support.
*Syslog Message*::
Call home for FILESYSTEM DISK RAWSIZE SHRANK
*Parameters*::
*subject* (STRING): AutoSupport subject or title for this event.
