---
sidebar: sidebar
permalink: cmd-start-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: cmd.start events
---

= cmd.start events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== cmd.start.unsuccessful
*Severity*::
ERROR
*Description*::
This message occurs when the Counter Manager daemon (cmd) fails to start. The failure impacts the continuous archiving of performance data, which is used by technical support to troubleshoot system issues.
*Corrective Action*::
The startup failure might be due to improper permissions for the '/mroot/etc/log' directory, or a full disk. Verify that the permissions of the '/mroot/etc/log' directory are 'rwxr-xr-x' by executing the 'fsecurity show /vol/vol0/etc/log' command from the nodeshell. Verify that the '/mroot' file system is not full. After fixing the cause of the failure, restart the cmd by running the 'spmctl -e -h cmd' command from the freebsd shell.
*Syslog Message*::
The cmd startup failed.
*Parameters*::
(None).
