---
sidebar: sidebar
permalink: config-bridge-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: config.bridge events
---

= config.bridge events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== config.bridge.adapter.invalid
*Severity*::
ERROR
*Description*::
This message occurs when an FC-to-SAS bridge is attached to an unsupported FC adapter port. Only QLogic(R) 4-Gb/s or 8-Gb/s adapters are supported.
*Corrective Action*::
Attach the FC-to-SAS bridge to a supported FC adapter port on the controller.
*Syslog Message*::
FC-to-SAS bridge %s S/N [%s] is attached to unsupported FC adapter port %s.
*Parameters*::
*bridgeName* (STRING): Name of the FC-to-SAS bridge.
*bridgeSerialNum* (STRING): Serial number of the FC-to-SAS bridge.
*adapterName* (STRING): Name of the associated FC host bus adapter.

== config.bridge.extra.port
*Severity*::
ERROR
*Description*::
This message occurs when both FC ports of an FC-to-SAS bridge are attached to the same controller.
*Corrective Action*::
Follow the defined Fabric or Stretch MetroCluster wiring guide.
*Syslog Message*::
Both FC ports of FC-to-SAS bridge %s S/N [%s] are attached to this controller.
*Parameters*::
*bridgeName* (STRING): Name of the FC-to-SAS bridge.
*bridgeSerialNum* (STRING): Serial number of the FC-to-SAS bridge.

== config.bridge.fw.mismatch
*Severity*::
ERROR
*Description*::
This message occurs when two or more attached FC-to-SAS bridges are running different firmware revisions.
*Corrective Action*::
For more information about downloading and installing updated firmware, check your support provider's web site or knowledgebase.
*Syslog Message*::
Two or more %s FC-to-SAS bridges are running different firmware revisions.
*Parameters*::
*bridgeModel* (STRING): Name of the FC-to-SAS bridge model.

== config.bridge.SAS.miswired
*Severity*::
ERROR
*Description*::
This message occurs when the SAS disk shelves behind an FC-to-SAS bridge are not wired in the correct order.
*Corrective Action*::
Follow the defined Fabric or Stretch MetroCluster wiring guide.
*Syslog Message*::
The SAS disk shelves behind FC-to-SAS bridge %s S/N [%s] are not correctly wired.
*Parameters*::
*bridgeName* (STRING): Name of the FC-to-SAS bridge.
*bridgeSerialNum* (STRING): Serial number of the FC-to-SAS bridge.

== config.bridge.SAS2Domain
*Severity*::
ERROR
*Description*::
This message occurs when a disk is multipathed to one SAS domain; that is, both ports of the disk are visible from the same bridge FC port.
*Corrective Action*::
Recable the disk shelf containing the specified disk, so that the two disk ports are in different SAS domains.
*Syslog Message*::
Disk %s is multipathed to the same SAS domain. The two disk ports must be in different SAS domains.
*Parameters*::
*disk* (STRING): Name of the disk.

== config.bridge.unsupp.shelf
*Severity*::
ALERT
*Description*::
This message occurs when an FC-to-SAS bridge discovers a disk shelf that it does not support.
*Corrective Action*::
Verify the bridge firmware is up-to-date with minimum FW rev required for support of this shelf type. If the bridge firmware supports the disk shelf but the error condition persists, remove the disk shelf.
*Syslog Message*::
FC-to-SAS %s bridge with S/N: %s WWN: %s has unsupported %s shelf type attached.
*Parameters*::
*bridgeType* (STRING): Type of FC-to-SAS bridge.
*bridgeSerialNum* (STRING): Serial number of the bridge.
*bridgeWWN* (STRING): World Wide Name of the bridge.
*shelfType* (STRING): Type of shelf.
