---
sidebar: sidebar
permalink: connectx-ibqsfpdumpdata-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: connectx.ibqsfpdumpdata events
---

= connectx.ibqsfpdumpdata events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== connectx.IbQsfpDumpData
*Severity*::
ERROR
*Description*::
This message occurs when InfiniBand retimer programming fails due to a quad small form-factor pluggable (QSFP) transceiver parse error, and 128 bytes of QSFP data are dumped.
*Corrective Action*::
Automatic retry of InfiniBand retimer programming will be done and an AutoSupport(tm) message will be generated if two retries fail.
*Syslog Message*::
InfiniBand retimer programming failed on port %s due to %s. Dumping registers: %s.
*Parameters*::
*port_str* (STRING): InfiniBand port in which the cable is plugged.
*reason* (STRING): Reason for the failure of InfiniBand retimer programming.
*qsfp_data* (STRING): Contents of QSFP data registers from offset 128 to 256 in hexadecimal notation.
