---
sidebar: sidebar
permalink: cpeer-dns-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: cpeer.dns events
---

= cpeer.dns events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== cpeer.dns.family.mismatch
*Severity*::
ERROR
*Description*::
This message occurs when an attempt is made to resolve and insert a stable address that is a Domain Name System (DNS) style host name. If it resolves to an address family that does not match the family style specified for the cluster peer relationship, it is indicative of incorrect addresses being provided by the administrator or DNS configuration issues. Stable addresses are typically provided by the administrator during cluster peer creation and can be modified by modifying the peer relationship.
*Corrective Action*::
Correct the stable IP address by using the 'cluster peer modify' command. Ensure that LIFs of the appropriate address family exist on both the local cluster and the remote peer. Confirm that the DNS services are appropriately specified by using the 'vserver services dns show' command. Also, the DNS server in question should be configured correctly to be able to resolve the DNS style host name to an IP address belonging to the appropriate address family. If you need further assistance, contact NetApp technical support.
*Syslog Message*::
Host name %s of peer cluster %s resolved to %s, which does not match the peer relationship's selected address type.
*Parameters*::
*addr* (STRING): Peer cluster host name that is being inserted.
*peer* (STRING): Name of the peer cluster for which an address family mismatch was seen.
*resolved_address* (STRING): Address resolved to, which belongs to the incorrect address family.
