---
sidebar: sidebar
permalink: exports-dns-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: exports.dns events
---

= exports.dns events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== exports.dns.config
*Severity*::
ERROR
*Description*::
This message occurs when a name services lookup request finds that DNS is configured as an ns-switch source for hosts, but DNS is not configured for the Vserver. Name services lookups using DNS do not function.
*Corrective Action*::
Check the ns-switch sources for hosts database configured for the Vserver using "vserver services name-service ns-switch show -database hosts" and the DNS configuration for the Vserver using "vserver services name-service dns show". Either remove DNS as an ns-switch source, or configure DNS using the "vserver services name-service dns create" command.
*Syslog Message*::
DNS is configured as a ns-switch source for hosts, but the DNS configuration is not found for Vserver "%s".
*Parameters*::
*vserver* (STRING): Name of the Vserver on which the problem is occurring.
