---
sidebar: sidebar
permalink: fci-link-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: fci.link events
---

= fci.link events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== fci.link.break
*Severity*::
ERROR
*Description*::
This message occurs when the Fibre Channel adapter detects a break in the link.
*Corrective Action*::
If the adapter is in use, check the cabling.
*Syslog Message*::
Link break detected on Fibre Channel adapter %s.
*Parameters*::
*adapterName* (STRING): Name of the associated Fibre Channel host bus adapter.

== fci.link.break.shelf.fw.update
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the Fibre Channel adapter detects a break in the link due to a shelf firmware update being performed.
*Corrective Action*::
No corrective action is required. This is expected behavior when firmware is being downloaded to a shelf.
*Syslog Message*::
Link break detected on Fibre Channel adapter %s while downloading shelf firmware.
*Parameters*::
*adapterName* (STRING): Name of the associated Fibre Channel host bus adapter.

== fci.link.error
*Severity*::
NOTICE
*Description*::
This message occurs when the Fibre Channel adapter cannot recover the link and the link is going offline.
*Corrective Action*::
(None).
*Syslog Message*::
Could not recover link on Fibre Channel adapter %s after %d seconds. Taking the adapter offline.
*Parameters*::
*adapterName* (STRING): Name of the associated Fibre Channel host bus adapter.
*downTime* (INT): Amount of time that the link is down.
