---
sidebar: sidebar
permalink: flexcache-originfull-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: flexcache.originfull events
---

= flexcache.originfull events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== flexcache.originFull
*Severity*::
ALERT
*Description*::
This message occurs when a FlexCache(R) origin volume cannot serve data to cache volume because origin volume is full. The cache volume might therefore not be able to serve data to its clients until the origin has free space.
*Corrective Action*::
Ensure that the origin volume has free space.
*Syslog Message*::
FlexCache origin volume with Name %s MSID %lu on Vserver Name %s UUID %s may not be able to serve data to FlexCache volume with Vserver UUID %s and MSID %lu because origin volume is full.
*Parameters*::
*originVolumeName* (STRING): Origin Volume name.
*originMsid* (LONGINT): Master data set identifier (MSID) of the origin volume.
*originVserverName* (STRING): Vserver name of the origin volume.
*originVserverUuid* (STRING): Vserver UUID of the origin volume.
*cacheVserverUuid* (STRING): Vserver UUID of the FlexCache volume.
*cacheMsid* (LONGINT): MSID of the FlexCache volume.
