---
sidebar: sidebar
permalink: ha-panicinfonotsentic-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: ha.panicinfonotsentic events
---

= ha.panicinfonotsentic events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== ha.panicInfoNotSentIC
*Severity*::
NOTICE
*Description*::
This message occurs when a node cannot send panic information to its high-availability (HA) partner over the HA interconnect due to an HA interconnect error. The HA partner might still initiate takeover if it detects that the partner is down by other means, and takeover of the panicking node is allowed.
*Corrective Action*::
(None).
*Syslog Message*::
Local node cannot send a panic information message to its HA partner due to an HA interconnect error: %s (error code: %d). Partner name: %s. Partner system ID: %llu.
*Parameters*::
*error* (STRING): Reason the node cannot send panic information to its HA partner.
*error_code* (INT): Specific error generated by the HA Interconnect. Example error codes: 1 (ERR_ICDOWN): Interconnect is down 4 (ERR_SYSERROR): System error 5 (ERR_ICERROR): Interconnect error 6 (ERR_OUTOFMEMORY): Out of memory 11 (ERR_SENDSIZE): Send size is too large 19 (ERR_CKSUM): Checksum error
*partner_name* (STRING): Name of the HA partner.
*partner_systemid* (LONGINT): System ID of the HA partner.
