---
sidebar: sidebar
permalink: ha-panicinforcvbadvrsn-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: ha.panicinforcvbadvrsn events
---

= ha.panicinforcvbadvrsn events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== ha.panicInfoRcvBadVrsn
*Severity*::
NOTICE
*Description*::
This message occurs when the version of the panic information received from the high-availability (HA) partner is not equal to the expected version. The receiving node will discard this panic information message. A takeover might still occur if the local node detects that its HA partner is down by other means, and takeover of the panicking node is allowed.
*Corrective Action*::
(None).
*Syslog Message*::
Panic information message received from the HA partner is the wrong version. Expected version: %u. Received version: %u. Partner name: %s. Partner system ID: %llu.
*Parameters*::
*expected_version* (LONGINT): Expected version of the panic information.
*received_version* (LONGINT): Received version of the panic information.
*partner_name* (STRING): Name of the HA partner.
*partner_systemid* (LONGINT): System ID of the HA partner.
