---
sidebar: sidebar
permalink: ic-linkspeeddegraded-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: ic.linkspeeddegraded events
---

= ic.linkspeeddegraded events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== ic.linkSpeedDegraded
*Severity*::
ERROR
*Description*::
This message occurs when the high-availability (HA) interconnect detects a degraded link speed.
*Corrective Action*::
For externally connected links, make sure that the interconnect cables are connected properly and that small form-factor pluggable (SFP) modules, if applicable, are seated properly on both controllers. For internally connected links, disable and reenable the links one at a time by using the (privilege: advanced) "system ha interconnect link off" and "system ha interconnect link on" commands. If the problem persists, contact NetApp technical support.
*Syslog Message*::
HA interconnect: Link speed of link #%d degraded. Current: %s, expected: %s.
*Parameters*::
*link_num* (INT): Number that identifies the link.
*link_speed* (STRING): Current link speed.
*expected_speed* (STRING): Link speed expected for the HA interconnect device.
