---
sidebar: sidebar
permalink: lmgr-session-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: lmgr.session events
---

= lmgr.session events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
lmgr.session EMS events occur when a SpinNP session has failed, which causes session-scoped (e.g.

== lmgr.session.cleanup.stalled
*Severity*::
NOTICE
*Description*::
This event occurs when session cleanup for a SpinNP session has stalled.
*Corrective Action*::
If this event occurs frequently, contact NetApp technical support.
*Syslog Message*::
(None).
*Parameters*::
*initiator* (STRING): The blade ID of the initiator.
*uniquifier* (STRING): The session uniquifier.
*target* (STRING): The blade ID of the target.
*retrigger_count* (INT): Number of times cleanup was retriggered before giving up.

== lmgr.session.failed
*Severity*::
INFORMATIONAL
*Description*::
This event occurs when a SpinNP session has failed, which causes session-scoped (e.g. CIFS) locks on the D-blade to be dropped. Only affects locks acquired using the failed session. This will cause clients to see a service disruption until they re-connect to the server.
*Corrective Action*::
None -- clients will automatically try to reconnect to the server, re-locking files as necessary.
*Syslog Message*::
Dropped session-scoped locks from session %s:%s:%s due to failed session.
*Parameters*::
*initiator* (STRING): The blade ID of the initiator.
*uniquifier* (STRING): The session uniquifier.
*target* (STRING): The blade ID of the target.
