---
sidebar: sidebar
permalink: lun-oovc-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: lun.oovc events
---

= lun.oovc events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== LUN.oovc.rebuild.done
*Severity*::
NOTICE
*Description*::
This message occurs when the rebuilding of the Out Of Volume Container (OOVC) file is complete.
*Corrective Action*::
(None).
*Syslog Message*::
The OOVC has been rebuilt for the volume %s (DSID %llu).
*Parameters*::
*volume_name* (STRING): Name of the volume for which the OOVC file was rebuilt.
*volume_dsid* (LONGINT): Data Set ID (DSID) of the volume for which the OOVC file was rebuilt.

== LUN.oovc.version.mismatch
*Severity*::
ERROR
*Description*::
This message occurs when a version mismatch is detected for the Out Of Volume Container (OOVC) metafile.
*Corrective Action*::
Rebuild the OOVC metafile for the volume by running the 'lun rescan -build-oovc' command.
*Syslog Message*::
A version mismatch has been detected for the OOVC metafile in volume %s (DSID %llu).
*Parameters*::
*volume_name* (STRING): Name of the volume for which a version mismatch of the OOVC metafile has been detected.
*volume_dsid* (LONGINT): Data Set ID (DSID) of the volume for which a version mismatch of the OOVC metafile has been detected.
