---
sidebar: sidebar
permalink: mgmt-fsecurity-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: mgmt.fsecurity events
---

= mgmt.fsecurity events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== mgmt.fsecurity.failure
*Severity*::
ERROR
*Description*::
This message occurs when applying configuration of fsecurity fails.
*Corrective Action*::
Wait for a while and reapply using the "vserver security file-directory apply" command. See the "vserver security file-directory" man pages for information, or if the problem persists, contact NetApp technical support.
*Syslog Message*::
Failed to apply file security policy. Error: %s.
*Parameters*::
*reason* (STRING): Reason for the failure.
*vservername* (STRING): Name of the vserver.

== mgmt.fsecurity.success
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when a file security policy was applied successfully after a previous failure.
*Corrective Action*::
(None).
*Syslog Message*::
(None).
*Parameters*::
*vservername* (STRING): Name of the Vserver.
