---
sidebar: sidebar
permalink: monitor-nvramlowbattery-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: monitor.nvramlowbattery events
---

= monitor.nvramlowbattery events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== monitor.nvramLowBattery
*Severity*::
EMERGENCY
*Description*::
This message occurs when the NVRAM battery is at a dangerously low power level.
*Corrective Action*::
Replace the NVRAM battery.
*Syslog Message*::
NVRAM battery is dangerously low.
*Parameters*::
(None).

== monitor.nvramLowBattery.notice
*Severity*::
NOTICE
*Description*::
This message occurs when a low battery situation exists. The timeout[123] values are duplicated as a convenience for the Syslog message, which prints out the value three times.
*Corrective Action*::
Replace the NVRAM battery.
*Syslog Message*::
If the NVRAM battery is dangerously low, the system shuts down automatically every %d hours to encourage you to replace it. If you reboot the system it will run for another %d hours before shutting down.
*Parameters*::
*timeout1* (INT): Timeout value.
*timeout2* (INT): Timeout value.
*timeout3* (INT): Timeout value.
