---
sidebar: sidebar
permalink: moveagent-swapvldb-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: moveagent.swapvldb events
---

= moveagent.swapvldb events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== moveagent.swapvldb.fail
*Severity*::
ALERT
*Description*::
This message occurs when a 'volume move' operation finishes moving the volume to the destination but fails to update the volume location database (VLDB). Failing to update the VLDB causes continued attempts to access the original location instead of the new location. The system continues to retry the operation until it is successful. In the time between the failure and a successful retry, there might be disruption to data access on the volume being moved.
*Corrective Action*::
Monitor the volume move job for 30 minutes by running the "volume move show -vserver <vservername> -volume <volName%gt;" command. If the cutover phase continues to fail while trying to swap VLDB records, contact NetApp technical support.
*Syslog Message*::
Unable to finish the volume move operation for DSID %llu. Failed to complete the swap VLDB operation successfully.
*Parameters*::
*volume_dsid* (LONGINT): Destination volume data set ID (DSID).

== moveagent.swapvldb.sync.fail
*Severity*::
ERROR
*Description*::
This message occurs when a 'volume move' operation finishes moving the volume to the destination but fails to replicate swapping of volume location database (VLDB) to the MetroCluster(tm) sync destination.
*Corrective Action*::
Monitor the volume move job. If the problem persists, contact NetApp technical support
*Syslog Message*::
Unable to finish replicating swap VLDB operation to MetroCluster(tm) destination for the volume move operation for DSID %llu.
*Parameters*::
*volume_dsid* (LONGINT): Destination volume Data Set ID (DSID).
