---
sidebar: sidebar
permalink: nblade-nosmbvernegotiated-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nblade.nosmbvernegotiated events
---

= nblade.nosmbvernegotiated events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Nblade.noSmbVerNegotiated
*Severity*::
ERROR
*Description*::
This message occurs when Data ONTAP(R) does not support any of the SMB protocol versions sent by the client for negotiation.
*Corrective Action*::
Ensure that the client supports at least one of the enabled SMB versions. You can determine whether an SMB version is enabled by running the "vserver cifs options show" command in advanced mode.
*Syslog Message*::
For Vserver "%s", Data ONTAP(R) could not negotiate with the client "%s" because it does not support any of the SMB protocol versions that the client sent in the list "%s".
*Parameters*::
*vserverName* (STRING): Vserver associated with this operation.
*clientIp* (STRING): IP address of the client attempting to negotiate.
*clientVersionList* (STRING): List of the SMB protocol versions sent by the client.
