---
sidebar: sidebar
permalink: nblade-vscanvirusdetected-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nblade.vscanvirusdetected events
---

= nblade.vscanvirusdetected events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Nblade.vscanVirusDetected
*Severity*::
ERROR
*Description*::
This message occurs when a vscan server reports an error to the storage system. Normally this indicates that a virus has been found by the vscan server; however, other error conditions on the vscan server can result in this event. Client access to the file is denied. The vscan server might, depending on its settings and configuration, clean the file, quarantine it, or delete it.
*Corrective Action*::
Check the log of the vscan (antivirus) server reported in the syslog message to see if it was able to successfully quarantine or delete the infected file. If it was not able to do so, a system administrator might want to manually delete the file.
*Syslog Message*::
Possible virus detected. Vserver: %s, vscan server IP: %s, file path: %s, client IP: %s, SID: %s, vscan engine status: %u, vscan engine result string: %s.
*Parameters*::
*vserverName* (STRING): Name of the Vserver associated with this operation.
*vscanServerIp* (STRING): IP address of the vscan server.
*filePath* (STRING): Path of the file that was found to be infected.
*clientIp* (STRING): IP address of the client.
*SID* (STRING): SID of the client.
*vscanEngineStatus* (INT): Status code returned by the vscan server.
*vscanEngineResultString* (STRING): Result string returned by the vscan server.
*object_type* (STRING): Type of the resource object under notification.
*object_uuid* (STRING): UUID of the resource object.
