---
sidebar: sidebar
permalink: nblade-cifssametreepersessnotice-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nblade.cifssametreepersessnotice events
---

= nblade.cifssametreepersessnotice events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Nblade.cifsSameTreePerSessNotice
*Severity*::
NOTICE
*Description*::
This message occurs when the number of connections to the same share allowed per session nears the configured limit. Upon reaching this limit, any further requests to establish another connection to that share are denied until some connections to the share are released. This typically indicates abnormal client behavior.
*Corrective Action*::
Inspect the application using the connection, and also monitor the other applications on the client. The client might be operating incorrectly due to a faulty application running on it. Rebooting the client might also be helpful. In some cases, clients are operating as expected but require a higher threshold, which you can set by using the (privilege: advanced) "cifs option modify -max-same-tree-connect-per-session" command.
*Syslog Message*::
Received %d connection requests to the same share, nearing the configured limit of %d, from one session: clientIP:port %s:%d, share: "%s", user: "%s", vserver: "%s".
*Parameters*::
*currentCount* (INT): Current count of the connections on the session.
*maxValue* (INT): Maximum allowed connections on the session.
*IpAddress* (STRING): IP address of the client from which multiple share connections have been attempted.
*port* (INT): Port number of the client from which the TCP connection has been established.
*shareName* (STRING): Name of the share to which the client is attempting connection.
*userName* (STRING): User that is attempting to connect to the share.
*vserverName* (STRING): Vserver associated with this operation.
