---
sidebar: sidebar
permalink: nvmf-qos-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nvmf.qos events
---

= nvmf.qos events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== nvmf.qos.mismatch.policy.r2
*Severity*::
ERROR
*Description*::
This message occurs when an NVMe over Fabrics (NVMe-oF) target subsystem contains namespaces that have different quality of service (QoS) policies which might affect the I/O of the namespaces with higher QoS policies. It is best practice to have the same QoS policy across all namespaces within a subsystem.
*Corrective Action*::
Determine which namespaces exist within the subsystem NQN by using the "vserver nvme subsystem map show" command. Verify that these namespaces share the same QoS policy by using the "vserver nvme namespace show -fields path,qos-policy-group" command.
*Syslog Message*::
NVMe-oF target subsystem NQN %s contains %d namespaces that do not have the same QoS policy.
*Parameters*::
*subsystem_nqn* (STRING): NVMe Qualified Name (NQN) of the subsystem.
*ns_count* (INT): Number of namespaces that do not match.

== nvmf.qos.mismatched.policy
*Severity*::
ERROR
*Description*::
This message occurs when an NVMe-oF target subsystem contains namespaces that have different QoS policies.
*Corrective Action*::
Determine which volumes exist within the named subsystem NQN by using the "vserver nvme subsystem map show" command. Verify that these volumes share the same QoS policy by using the "volume show -fields name,qos-policy-group" command.
*Syslog Message*::
NVMe-oF target subsystem NQN %s contains %d namespaces that do not have the same QoS policy.
*Parameters*::
*subsystem_nqn* (STRING): NVMe Qualified Name (NQN) of the subsystem.
*ns_count* (INT): Number of namespaces that do not match.

== nvmf.qos.viodet.regfail
*Severity*::
ERROR
*Description*::
This message occurs when the Quality-of-Service (QoS) subsystem fails to register for updates during initialization due to an internal error (e.g. there is not enough system memory available). As a result, workloads might not meet their minimum throughput or their service-level objectives (SLOs).
*Corrective Action*::
The registration will continue to be retried. If this message continues to occur, perform a planned takeover/giveback sequence to reset the reporting node nondisruptively by using the "takeover -ofnode (reporting_node)" and "giveback -ofnode (reporting_node)" commands. If the problem persists, contact Contact NetApp technical support..
*Syslog Message*::
Failed to register for violation detection updates. QoS min-throughput might operate in a limited capacity.
*Parameters*::
*errorCode* (INT): Error code that was returned during registration.
