---
sidebar: sidebar
permalink: perfstatd-dir-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: perfstatd.dir events
---

= perfstatd.dir events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== perfstatd.dir.permission
*Severity*::
ERROR
*Description*::
This message occurs when the perfstat daemon (perfstatd) startup fails due to improper permissions for the '/mroot/etc/log' directory. This failure impacts the continuous archiving of performance data that technical support uses to troubleshoot performance issues.
*Corrective Action*::
Verify that the permissions of the '/mroot/etc/log' directory are 'rwxr-xr-x' by executing the 'fsecurity show /vol/vol0/etc/log' command from the nodeshell. After correcting the permissions for this directory, restart perfstatd by executing the 'spmctl -e -h perfstatd' command from the freebsd shell.
*Syslog Message*::
The perfstat daemon startup failed due to improper directory permissions.
*Parameters*::
(None).
