---
sidebar: sidebar
permalink: scsiblade-object-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: scsiblade.object events
---

= scsiblade.object events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== scsiblade.object.out.of.sync
*Severity*::
ERROR
*Description*::
This message occurs when a SAN management event receives a timeout error due to network congestion in the system and all efforts of recovery fail. The specific SAN object for which the management event is intended will be out of sync and will have different values in cache and in persistent store. Access to LUNs within the Vserver might be affected.
*Corrective Action*::
Contact NetApp technical support. For further information about correcting the problem, see the knowledgebase article 2017369.
*Syslog Message*::
A SAN management event received a timeout error due to network congestion. Management event %llu on Vserver %s left the SAN object's cache copy out of sync with information in the persistent store. Access to LUNs within the Vserver might be affected.
*Parameters*::
*opcode* (LONGINT): Operation code.
*vserver* (STRING): Name or UUID of the Vserver.
