---
sidebar: sidebar
permalink: secd-rpc-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: secd.rpc events
---

= secd.rpc events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== secd.rpc.authRequest.blocked
*Severity*::
ALERT
*Description*::
This message occurs when a user with the same domain and same client IP address is blocked due to continuous authentication requests with an invalid login password.
*Corrective Action*::
Check if there is an unexpected increase in the number of authentication requests with an invalid login password from a particular CIFS client. Use "statistics show -raw -object secd -instance secd -counter num_rpcs_blocked_due_to_wrong_password" command to check the number of clients blocked due to an invalid password.
*Syslog Message*::
Too many CIFS authentication attempts with an invalid password from a client with IP "%s", user name "%s" and domain "%s" on SVM "%s".
*Parameters*::
*clientIP* (STRING): IP address of the client that has been blocked.
*userName* (STRING): User who is trying to mount with an invalid password.
*domain* (STRING): Domain to which the user belongs.
*vserverName* (STRING): Storage virtual machine(SVM) associated with this operation.

== secd.rpc.server.ready
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when SecD successfully loads the configuration and is ready to serve all RPCs.
*Corrective Action*::
(None).
*Syslog Message*::
SecD is ready to serve all RPCs.
*Parameters*::
(None).

== secd.rpc.server.request.dropped
*Severity*::
ERROR
*Description*::
This message occurs when a remote procedure call(RPC) is dropped by SecD due to a lack of memory space. It might occur either when SecD receives too many requests than it can handle or when a number of requests have accumulated due to server connectivity issues.
*Corrective Action*::
Check whether there is an unexpected increase in the number of authentication requests from NFS/CIFS clients. Verify that there are no connectivity issues to the external servers like DNS, LDAP, and DC.
*Syslog Message*::
RPC "%s" that was sent from "%s" was dropped by SecD due to a lack of memory space.
*Parameters*::
*rpcName* (STRING): Name of the RPC that has been dropped.
*callerName* (STRING): Caller of the RPC that has been dropped.
