---
sidebar: sidebar
permalink: sfu-badbridgeshelfconfig-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sfu.badbridgeshelfconfig events
---

= sfu.badbridgeshelfconfig events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sfu.badBridgeShelfConfig
*Severity*::
ALERT
*Description*::
This message occurs when the disk shelf firmware update aborts because it cannot contact the two peer FC-to-SAS bridges.
*Corrective Action*::
Make sure that the storage controller is correctly cabled to the two peer FC-to-SAS bridges and that the bridges are correctly cabled to the SAS disk shelves. Then retry the (advanced privilege) "storage shelf firmware update" command.
*Syslog Message*::
Firmware update aborted on disk shelf %s.shelf%d module %s. Unable to contact two peer FC-to-SAS bridges.
*Parameters*::
*channelName* (STRING): Name of the adapter port or switch port of the disk shelf that aborted the firmware update.
*shelfId* (INT): ID of the disk shelf that aborted the firmware update.
*module* (STRING): Module that aborted the firmware update.
