---
sidebar: sidebar
permalink: shelf-config-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: shelf.config events
---

= shelf.config events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== shelf.config.mixed
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when a stand-alone system's storage configuration is a mixture of redundant paths and single paths.
*Corrective Action*::
(None).
*Syslog Message*::
System is using a mixture of single path, multi-path or quad-path storage configurations.
*Parameters*::
(None).

== shelf.config.mixedha
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when an HA system's storage configuration is a mixture of redundant paths and single paths.
*Corrective Action*::
(None).
*Syslog Message*::
System is using a mixture of single path, multi-path or quad-path HA storage configurations.
*Parameters*::
(None).

== shelf.config.mpha
*Severity*::
INFORMATIONAL
*Description*::
This event is generated at the Filer boot time, when it is a HA configuration and all the storage shelf enclosures accessible by the Filer have redundant paths. This message is for informational purpose only.
*Corrective Action*::
(None).
*Syslog Message*::
All attached storage on the system is multi-pathed HA.
*Parameters*::
(None).

== shelf.config.multipath
*Severity*::
INFORMATIONAL
*Description*::
This event is generated at the Filer boot time, when it is a stand alone configuration and all the storage shelf enclosures accessible by the Filer have redundant paths. This message is for informational purpose only.
*Corrective Action*::
(None).
*Syslog Message*::
All attached storage on the system is multi-pathed.
*Parameters*::
(None).

== shelf.config.qpha
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when an HA system's storage configuration is quad-path.
*Corrective Action*::
(None).
*Syslog Message*::
System storage is in a quad-path HA configuration.
*Parameters*::
(None).

== shelf.config.quadpath
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when a stand-alone system's storage configuration is quad-path.
*Corrective Action*::
(None).
*Syslog Message*::
System storage is in a quad-path configuration.
*Parameters*::
(None).

== shelf.config.single
*Severity*::
INFORMATIONAL
*Description*::
This event is generated at the Filer boot time, when it is a stand alone configuration and all the storage shelf enclosures accessible by the Filer have only one active path. This message is for informational purpose only.
*Corrective Action*::
(None).
*Syslog Message*::
System is using single path attached storage only.
*Parameters*::
(None).

== shelf.config.spha
*Severity*::
INFORMATIONAL
*Description*::
This event is generated at the Filer boot time, when it is a HA configuration and all the storage shelf enclosures accessible by the Filer have only one active path. This message is for informational purpose only.
*Corrective Action*::
(None).
*Syslog Message*::
System is using single path HA attached storage only.
*Parameters*::
(None).

== shelf.config.tomixed
*Severity*::
NOTICE
*Description*::
This message occurs in a stand-alone system when the storage configuration changes from a single-path, multi-path, or quad-path configuration, to a mixed path configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to a mixture of single path, multi-path or quad-path storage configurations.
*Parameters*::
(None).

== shelf.config.tomixedha
*Severity*::
NOTICE
*Description*::
This message occurs in an HA system when the storage configuration changes from a single-path HA, multi-path HA, or quad-path HA configuration to a mixed path HA configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to a mixture of single, multi-path or quad-path storage configurations.
*Parameters*::
(None).

== shelf.config.tompha
*Severity*::
INFORMATIONAL
*Description*::
This event is generated by the periodic storage health monitor process in a HA Filer configuration, when the Filer storage configuration changes from the single path HA configuration to the multi-path HA configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to multi-path HA attached storage
*Parameters*::
(None).

== shelf.config.tomultipath
*Severity*::
INFORMATIONAL
*Description*::
This event is generated by the periodic storage health monitor process in a stand alone Filer configuration, when the Filer storage configuration changes from the single-path configuration to the multi path configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to multi-path attached storage
*Parameters*::
(None).

== shelf.config.toqpha
*Severity*::
NOTICE
*Description*::
This message occurs in an HA system when the storage configuration changes to quad-path.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to a quad-path storage configuration.
*Parameters*::
(None).

== shelf.config.toquadpath
*Severity*::
NOTICE
*Description*::
This message occurs in a stand-alone system. System has transitioned to a quad-path storage configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to quad-path attached storage
*Parameters*::
(None).

== shelf.config.tosingle
*Severity*::
INFORMATIONAL
*Description*::
This event is generated by the periodic storage health monitor process in a stand alone Filer configuration, when the Filer storage configuration changes from the multi-path configuration to the single path configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to single path attached storage
*Parameters*::
(None).

== shelf.config.tospha
*Severity*::
INFORMATIONAL
*Description*::
This event is generated by the periodic storage health monitor process in a HA Filer configuration, when the Filer storage configuration changes from the multi-path HA configuration to the single path HA configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System has transitioned to single path HA attached storage
*Parameters*::
(None).

== shelf.config.toTripath
*Severity*::
NOTICE
*Description*::
This message occurs when a stand-alone system changes to a tri-path storage configuration.
*Corrective Action*::
(None).
*Syslog Message*::
System transitions to a tri-path storage configuration.
*Parameters*::
(None).

== shelf.config.toTripathHA
*Severity*::
NOTICE
*Description*::
This message occurs in a high-availability (HA) system when the storage configuration changes to tri-path.
*Corrective Action*::
(None).
*Syslog Message*::
System transitions to a tri-path HA storage configuration.
*Parameters*::
(None).

== shelf.config.tripath
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when a stand-alone system's storage configuration is tri-path.
*Corrective Action*::
(None).
*Syslog Message*::
System storage is in a tri-path configuration.
*Parameters*::
(None).

== shelf.config.tripathHA
*Severity*::
NOTICE
*Description*::
This message occurs at system boot time, when a high-availability (HA) system's storage configuration is tri-path.
*Corrective Action*::
(None).
*Syslog Message*::
System storage is in a tri-path HA storage configuration.
*Parameters*::
(None).
