---
sidebar: sidebar
permalink: sp-heartbeat-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sp.heartbeat events
---

= sp.heartbeat events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sp.heartbeat.resumed
*Severity*::
INFORMATIONAL
*Description*::
This event is generated when the appliance detects resumption of Service Processor (SP) heartbeat notifications indicating that the Service Processor is now available. The earlier issue indicated by the sp.heartbeat.stopped event has been resolved.
*Corrective Action*::
(None).
*Syslog Message*::
Received %s heartbeat from the Service Processor (SP).
*Parameters*::
*type* (STRING): Heartbeat from Service Processor can be of the following types: 1. IPMI Heartbeat 2. Packetized heartbeat. This parameter specifies which type of heartbeat this event corresponds to.

== sp.heartbeat.stopped
*Severity*::
INFORMATIONAL
*Description*::
This event is generated when Data ONTAP does not receive Service Processor (SP) heartbeat notifications. The Service Processor and Data ONTAP exchange heartbeat messages so that they can detect when one or the other is unavailable. This event is generated when Data ONTAP has not received an expected heartbeat message from the Service Processor.
*Corrective Action*::
1. Connect to the SP CLI and issue: 1.1. sp version 1.2. priv set advanced 1.3. sp log debug 1.4. sp log messages 2. Run SP system diagnostics. 3. Consult Service Processor Troubleshooting Guide.
*Syslog Message*::
Have not received a %s heartbeat from the Service Processor (SP) in last %d seconds.
*Parameters*::
*type* (STRING): Heartbeat from Service Processor can be of the following types: 1. IPMI Heartbeat 2. Packetized heartbeat. This parameter specifies which type of heartbeat this event corresponds to.
*time* (INT): Heartbeats have not been received from the Service Processor (SP) for this period of time in seconds.
