---
sidebar: sidebar
permalink: sp-notconfigured-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sp.notconfigured events
---

= sp.notconfigured events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sp.notConfigured
*Severity*::
ERROR
*Description*::
This message occurs weekly to remind you to configure the Service Processor (SP). The SP is a physical device that is incorporated into your system to provide remote access and remote management capabilities. To use the full functionality of the SP, you need to configure it first.
*Corrective Action*::
1. Use the 'system service-processor network modify' command to configure the SP. If necessary, use the 'system service-processor network show' command to obtain its MAC address. 2. Use the 'system service-processor network show' command to verify the SP network configuration. 3. Use the 'system service-processor autosupport invoke' command to verify that the SP can send AutoSupport email. Note that AutoSupport mailhosts and recipients must be properly configured in Data ONTAP(R) before issuing this command.
*Syslog Message*::
The system's Service Processor (SP) is not configured. Use the 'system service-processor network modify' command to configure it.
*Parameters*::
*object_type* (STRING): Type of resource object under notification. For this EMS, the object_type will always be NODE.
*object_uuid* (STRING): UUID of the resource object. For this EMS, the UUID will be of the node.
