---
sidebar: sidebar
permalink: sp-upd-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sp.upd events
---

= sp.upd events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sp.upd.bad.fw.package
*Severity*::
ERROR
*Description*::
This message occurs when the Service Processor (SP) daemon cannot extract the SP firmware version from the metadata file. Either the file cannot be opened, or the number cannot be found within the file.
*Corrective Action*::
Use the "system node image package delete" command to remove the corrupted package. If failures persist, contact NetApp technical support.
*Syslog Message*::
Service Processor daemon failed to read metadata from the image package.
*Parameters*::
*Package_Name* (STRING): Name of the SP firmware package being processed.

== sp.upd.fw.depot.full
*Severity*::
ERROR
*Description*::
This message occurs when a user downloads more than the supported number of Service Processor (SP) firmware packages to the local node.
*Corrective Action*::
Use the "system node image package delete" command to remove older packages. If failures persist, contact NetApp technical support.
*Syslog Message*::
Repository for SP image is full.
*Parameters*::
*available_sp_pkg_count* (INT): Number of SP firmware packages existing in the local node.
*max_num_of_sp_pkgs* (INT): Maximum number of supported SP packages in the local node.

== sp.upd.unzip.event
*Severity*::
ERROR
*Description*::
This message occurs when the Service Processor (SP) daemon cannot expand the compressed SP firmware packages for the local node. The expected package could either not be found, or it could not be expanded.
*Corrective Action*::
Use the "system node image package delete" command to remove the corrupted package. If failures persist, contact NetApp technical support.
*Syslog Message*::
Service Processor failed to decompress the image package.
*Parameters*::
*package_name* (STRING): SP firmware package name.
*sp_fw_update_type* (STRING): Type of SP firmware update being performed when the error was encountered.
