---
sidebar: sidebar
permalink: spm-coresegd-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: spm.coresegd events
---

= spm.coresegd events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== spm.coresegd.process.exit
*Severity*::
ALERT
*Description*::
This message occurs when the core segment server (coresegd) involuntarily terminates. The termination of this server impacts all core segmenting services provided by the node.
*Corrective Action*::
The system attempts to recover by restarting the node connectivity "process server". If the process does not restart within the threshold number of retries, then an AutoSupport(tm) message is sent. If your system is not configured to send AutoSupport messages and the issue persists, contact NetApp technical support.
*Syslog Message*::
The core segment server (coresegd) with ID %d exited as a result of %s. This server will attempt to restart.
*Parameters*::
*id* (INT): Process identifier.
*cause* (STRING): Plain text description of why the process terminated.
