---
sidebar: sidebar
permalink: spm-named-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: spm.named events
---

= spm.named events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== spm.named.process.exit
*Severity*::
ERROR
*Description*::
This message occurs when the Domain Name Service (DNS) name resolution daemon 'named' involuntarily exits. This error can have one or more causes and might be related to some recent or previous operations. The failure of this daemon can affect DNS zone-based access. In particular, the cluster might no longer be able to resolve DNS zone names to IP addresses and clients that connect to the zone using zone names.
*Corrective Action*::
While this problem persists, ensure that any new mounts use an IP address instead of a zone name. The system attempts to recover by restarting the subsystem. If the subsystem does not recover within the threshold number of retries, then an AutoSupport message is sent. If your system is not configured to send AutoSupport messages and the issue persists, contact NetApp technical support.
*Syslog Message*::
DNS name resolution daemon 'named' with ID %d exited as a result of signal %s. The service will attempt to restart.
*Parameters*::
*id* (INT): Process identifier.
*cause* (STRING): Plain text description of why the process exited.
