---
sidebar: sidebar
permalink: spm-envmgr-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: spm.envmgr events
---

= spm.envmgr events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== spm.envmgr.process.exit
*Severity*::
ERROR
*Description*::
This message occurs when the environmental monitoring daemon (env_mgr) involuntarily terminates. This daemon is responsible for environmental monitoring for this platform. This failure does not affect client access; however, environmental monitoring might be in a degraded state if the service fails to restart, which could result in an unpredicted shutdown if an adverse environmental condition or hardware failure occurs.
*Corrective Action*::
The system attempts to recover by restarting the subsystem. If the subsystem does not recover within the threshold number of retries, then an AutoSupport message is sent. If your system is not configured to send AutoSupport messages and the issue persists, call technical support.
*Syslog Message*::
Environmental monitoring daemon (env_mgr) with ID %d exited as a result of signal %s. The service will attempt to restart.
*Parameters*::
*id* (INT): Process identifier.
*cause* (STRING): Plain text description of why the process exited.
