---
sidebar: sidebar
permalink: spm-nchmd-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: spm.nchmd events
---

= spm.nchmd events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== spm.nchmd.process.exit
*Severity*::
ALERT
*Description*::
This message occurs when the Node Connectivity Health Monitor process (nchmd) involuntarily terminates. The termination of this process can affect node connectivity monitoring for SAS subsystem.
*Corrective Action*::
The system attempts to recover by restarting the node connectivity process. server. If the process does not restart within the threshold number of retries, then an AutoSupport message is sent. If your system is not configured to send AutoSupport messages and the issue persists, contact technical support.
*Syslog Message*::
Node Connectivity Health Monitor process (nchmd) with ID %d exited as a result of %s. This server will attempt to restart.
*Parameters*::
*id* (INT): Process identifier.
*cause* (STRING): Plain text description of why the process exited.
