---
sidebar: sidebar
permalink: usbmon-boot-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: usbmon.boot events
---

= usbmon.boot events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== usbmon.boot.device.failed
*Severity*::
ERROR
*Description*::
This message occurs when the Data ONTAP(R) module that is responsible for monitoring the health of the Universal Serial Bus (USB) boot devices determines that the associated boot device will fail all writes to the media.
*Corrective Action*::
Replace the device.
*Syslog Message*::
Boot device %s has become read-only.
*Parameters*::
*device* (STRING): Name of the device.

== usbmon.boot.device.pfa
*Severity*::
ERROR
*Description*::
This message occurs when the Data ONTAP(R) Universal Serial Bus (USB) boot device health monitor PFA (predictive failure analysis) determines that failure is forthcoming for the associated boot device.
*Corrective Action*::
Replace the device.
*Syslog Message*::
Failure predicted for boot device %s.
*Parameters*::
*device* (STRING): Name of the device.
