---
sidebar: sidebar
permalink: vifmgr-unabletohostmovedlif-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: vifmgr.unabletohostmovedlif events
---

= vifmgr.unabletohostmovedlif events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== vifmgr.unabletohostmovedlif
*Severity*::
NOTICE
*Description*::
This message occurs when an attempt to move a logical interface (LIF) IP address to a specific node/port failed, and a subsequent attempt was made to move that LIF to another location.
*Corrective Action*::
(None).
*Syslog Message*::
LIF %s (on virtual server %s), IP address %s, could not be hosted and is being moved to node %s, port %s (error %s).
*Parameters*::
*vifname* (STRING): Name of the LIF that is being moved.
*vsrvid* (STRING): Name of the virtual server identifier on which this LIF resides.
*vifip* (STRING): The logical interface's IP address that is being moved.
*tonode* (STRING): Name of the node to where the LIF is moving.
*toport* (STRING): Name of the port to where the LIF is moving.
*error* (STRING): Error that was reported.
