---
sidebar: sidebar
permalink: vifmgr-lifbeinghosted-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: vifmgr.lifbeinghosted events
---

= vifmgr.lifbeinghosted events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== vifmgr.lifbeinghosted
*Severity*::
NOTICE
*Description*::
This message occurs when a logical interface (LIF) IP address that was previously marked as down because no eligible ports could host this LIF is now being hosted. Data access through this LIF is again up.
*Corrective Action*::
(None).
*Syslog Message*::
LIF %s (on virtual server %s), IP address %s, previously marked as down, is now up and serving data on node %s, port %s.
*Parameters*::
*vifname* (STRING): Name of the LIF that is now being hosted.
*vsrvid* (STRING): Name of the virtual server identifier on which this LIF resides.
*vifip* (STRING): The logical interface's IP address that is now being hosted.
*tonode* (STRING): Name of the node where the LIF is currently being hosted.
*toport* (STRING): Name of the port where the LIF is currently being hosted.
