---
sidebar: sidebar
permalink: vsdr-nonfpvolonfpaggr-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: vsdr.nonfpvolonfpaggr events
---

= vsdr.nonfpvolonfpaggr events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== vsdr.nonFPVolOnFPAggr
*Severity*::
NOTICE
*Description*::
This message occurs when the source volume of an SVM disaster recovery (SVMDR) relationship residing on a non-FabricPool aggregate at the primary cluster is placed on a FabricPool aggregate at the secondary cluster.
*Corrective Action*::
Move the source volume of the SVMDR relationship from the non-FabricPool aggregate to a FabricPool aggregate at the primary cluster by using the "volume move start -vserver <vserver-name> -volume <volume-name> -destination-aggregate <aggregate>" command.
*Syslog Message*::
Source volume "%s" of the SVMDR relationship residing at a nonFabricPool aggregate at the primary cluster is placed on a FabricPool aggregate "%s" at the destination cluster.
*Parameters*::
*source_volume_name* (STRING): Name of the source volume on the non-FabricPool aggregate of the SVMDR relationship.
*dest_aggr_name* (STRING): Name of the destination FabricPool aggregate at the secondary cluster.
