---
sidebar: sidebar
permalink: wafl-takeover-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.takeover events
---

= wafl.takeover events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.takeover.nvram.missing
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the system does not find any WAFL(R) nvlog records to replay during takeover processing.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL takeover: No WAFL nvlog records were found to replay.
*Parameters*::
(None).

== wafl.takeover.nvram.warn
*Severity*::
ERROR
*Description*::
This message occurs when NVRAM loss is detected during takeover. Some updates might have been lost, but takeover is proceeding.
*Corrective Action*::
(Call support).
*Syslog Message*::
WAFL takeover: Last few seconds of updates to partner might be lost.
*Parameters*::
(None).

== wafl.takeover.vol.mType.inv
*Severity*::
ERROR
*Description*::
This message occurs when WAFL(R) attempts to take over a mirror volume that does not have a valid mirror-type attribute. This situation might be a direct result of an upgrade to a version of Data ONTAP(R) that requires the mirror-type attribute or as a result of a corruption.
*Corrective Action*::
This condition cannot be fixed by file system repair mechanisms such as wafliron. The data is not lost, but it is inaccessible to the administrator. To access the data, contact NetApp technical support. Alternatively, the administrator can destroy the mirror volume by using the 'volume delete -vserver vserver_name -volume vol_name' command.
*Syslog Message*::
The mirror type associated with the mirror volume %s%s%s is invalid.
*Parameters*::
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases where the volume name by itself is insufficient.

== wafl.takeover.vol.nomount
*Severity*::
ERROR
*Description*::
This message occurs during a takeover or switchover operation when the system discovers that a partner volume cannot be mounted because it is inconsistent.
*Corrective Action*::
The volume is inconsistent. Run wafliron to clear this inconsistency, and then contact technical support.
*Syslog Message*::
%s partner volume %s%s%s is not mounted because it is inconsistent.
*Parameters*::
*operation* (STRING): Whether this message refers to takeover or switchover.
*vol* (STRING): Volume name.
*app* (STRING): Application UUID.
*volident* (STRING): Unique volume identity when the volume name itself is insufficient.

== wafl.takeover.vol.offline
*Severity*::
ERROR
*Description*::
This message occurs during a takeover or switchover operation when the system discovers that a partner volume cannot be brought online because it is inconsistent. The volume is left unmounted.
*Corrective Action*::
The volume is inconsistent and is left unmounted. Run wafliron to clear this inconsistency, and then contact technical support.
*Syslog Message*::
%s partner volume %s%s%s cannot be brought online because it is inconsistent.
*Parameters*::
*operation* (STRING): Whether this message refers to takeover or switchover.
*vol* (STRING): Volume name.
*app* (STRING): Application UUID.
*volident* (STRING): Unique volume identity when the volume name itself is insufficient.

== wafl.takeover.vols.mounted
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the volumes are mounted during takeover.
*Corrective Action*::
(None).
*Syslog Message*::
(None).
*Parameters*::
(None).
