---
sidebar: sidebar
permalink: wafl-analytics-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.analytics events
---

= wafl.analytics events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.analytics.air.uh
*Severity*::
ALERT
*Description*::
This message occurs when the system detects an inconsistency in the file system analytics database. As a consequence, file system analytics has been disabled.
*Corrective Action*::
Turn file system analytics on again for the volume to initiate new consistent analytics.
*Syslog Message*::
The system detected an inconsistency in the file system analytics database associated with volume %s%s.
*Parameters*::
*volname* (STRING): Volume name.
*vserveruuid* (STRING): Universal Unique ID (UUID) of the volume's storage VM (SVM).

== wafl.analytics.corruption
*Severity*::
ALERT
*Description*::
This message occurs when a file system analytics record is corrupted. Instances of this message indicate low accuracy of the analytics data reported for the volume.
*Corrective Action*::
Please contact NetApp technical support for assistance.
*Syslog Message*::
A file system analytics record identified by analytics filehandle "%s" on the volume with DSID "%lu" was corrupted due to an unexpected error.
*Parameters*::
*afh* (STRING): Key identifies the corrupted file system analytics record.
*dsid* (LONGINT): DSID of the volume affected by the corrupted record.

== wafl.analytics.discardNotOk
*Severity*::
ERROR
*Description*::
This message occurs when the analytics subsystem discards a pending reminder work request due to an internal error. Repeated instances of this message indicate low accuracy of the analytics data reported for the volume.
*Corrective Action*::
Taking the volume offline and bringing it back online might resolve the issue. Find the name of the Vserver and volume using the "volume show -dsid <dsid>" command. Take the volume offline using the "volume offline" command, and then bring it back online by using the "volume online" command. If the problem persists or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
An analytics reminder work request was discarded due to an unexpected error. The corresponding volume DSID is "%lu". The error returned was: %s
*Parameters*::
*dsid* (LONGINT): Data set ID (DSID) of the volume affected by the discarded reminder work request.
*error* (STRING): Error returned by reminder processing.

== wafl.analytics.enterOverload
*Severity*::
NOTICE
*Description*::
This message occurs when the analytics subsystem is not keeping up with the amount of work being generated by the system. This could be an indication of an overloaded system in general. Analytics accounting might lag, and reported data might not be as current as the data that the subsystem usually reports.
*Corrective Action*::
The system should attempt to resolve the problems by itself. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
The analytics subsystem is not keeping up with the amount of work being generated by the system.
*Parameters*::
(None).

== wafl.analytics.exitOverload
*Severity*::
NOTICE
*Description*::
This message occurs when the analytics subsystem is performing normally and has caught up with its pending work.
*Corrective Action*::
(None).
*Syslog Message*::
The analytics subsystem is performing normally.
*Parameters*::
(None).

== wafl.analytics.init.fail
*Severity*::
ALERT
*Description*::
This message occurs when a volume fails to have a file system analytics database initialized.
*Corrective Action*::
Disable then re-enable file system analytics for the volume. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
Failed to initialize a file system analytics database for volume %s%s, %s.
*Parameters*::
*volname* (STRING): Volume name.
*vserveruuid* (STRING): Universal Unique ID (UUID) of the volume's storage VM (SVM).
*error* (STRING): Error message.

== wafl.analytics.languishing
*Severity*::
ALERT
*Description*::
This message occurs when the analytics subsystem is unable to make progress, which could be an indication of an unhealthy node or a larger systemic issue.
*Corrective Action*::
NetApp technical support
*Syslog Message*::
The analytics subsystem has languished for more than 900 seconds.
*Parameters*::
(None).

== wafl.analytics.offErr
*Severity*::
ALERT
*Description*::
This message occurs when file system analytics fails to turn off. This can cause incorrect file system analytics results.
*Corrective Action*::
Use the "volume show -dsid <dsid>" command to find the volume on which file system analytics failed to turn off, and then use the "volume analytics off" command to attempt to turn off file system analytics. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
File system analytics failed to turn off on the volume with DSID "%lu". Error: %d. Context: %s.
*Parameters*::
*dsid* (LONGINT): Data Set ID (DSID) of the volume on which file system analytics failed to turn off.
*error* (INT): Error code returned when file system analytics failed to turn off.
*context* (STRING): Which operation attempted to turn off the file system analytics.

== wafl.analytics.recover
*Severity*::
ALERT
*Description*::
This message occurs when a volume fails to recover the File System Analytics state after failing to start the initialization scanner. As a consequence, File System Analytics information might be unavailable or might not accurately reflect the volume's content.
*Corrective Action*::
Use the "volume analytics off" command to disable File System Analytics on the volume, and then use the "volume analytics on" command to enable File System Analytics. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
The File System Analytics state for volume DSID (%lu) was not recovered after the initialization scanner failed to start. Reason: %s.
*Parameters*::
*dsid* (LONGINT): Unique identifier (DSID) of the volume.
*error* (STRING): Error message.

== wafl.analytics.rename.scan
*Severity*::
NOTICE
*Description*::
This message occurs when a rename scan starts while file system analytics is in the "initializing" state. Rename scans can occur to update the file system analytics database when a multipart inode or a directory is renamed or relocated to a different directory.
*Corrective Action*::
(None).
*Syslog Message*::
A file system analytics rename scan has been initiated for the rename of a %s identified by file system analytics filehandle "%s" on the volume with DSID "%lu".
*Parameters*::
*file_type* (STRING): Identifies whether the scan is initiated for a multipart inode or a directory.
*fh* (STRING): Filehandle of the multipart inode or directory that is being renamed.
*dsid* (LONGINT): Data Set ID (DSID) of the volume the multipart inode or directory that is being renamed belongs to.

== wafl.analytics.rescan
*Severity*::
ALERT
*Description*::
This message occurs when the system detects an inconsistency in the file system analytics database. As a consequence, file system analytics information might be unavailable or might not accurately reflect the volume's content.
*Corrective Action*::
Turn file system analytics off and then on again for the volume. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
The system detected an inconsistency in the file system analytics database associated with volume %s%s.
*Parameters*::
*volname* (STRING): Volume name.
*vserveruuid* (STRING): Universal Unique ID (UUID) of the volume's storage VM (SVM).

== wafl.analytics.scan.fail
*Severity*::
ALERT
*Description*::
This message occurs when the "volume analytics on" command fails due to an internal error.
*Corrective Action*::
Resolve the error if possible. Disable File System Analytics using the "volume analytics off" command and then re-enable File System Analytics using the "volume analytics on" command. If problems persist or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
File System Analytics scan fails for volume "%s%s. Error: %s".
*Parameters*::
*volname* (STRING): Volume name.
*vserveruuid* (STRING): Universal Unique ID (UUID) of the volume's storage VM (SVM).
*error* (STRING): Error message.

== wafl.analytics.sp.valid.fail
*Severity*::
ERROR
*Description*::
This message occurs when enabling file system analytics on a volume fails because there is insufficient space in the volume.
*Corrective Action*::
Increase the volume size or free up space on the volume. Use the "volume modify" command to increase volume size.
*Syslog Message*::
Enabling file system analytics on %s "%s" in SVM "%s" with "%s" %s fails because there is insufficient free space.
*Parameters*::
*volDesc* (STRING): In this message a volume that has not transitioned is described as a "volume".
*volName* (STRING): Volume name.
*vserverName* (STRING): Name of the storage virtual machine (SVM) on which the volume resides.
*percentUsed* (STRING): Percentage of used space in the volume.
*usageDesc* (STRING): Contains "usage" for a FlexVol volume, and "usage in one of the FlexGroup volume constituents" for a FlexGroup volume.

== wafl.analytics.sp.valid.skip
*Severity*::
NOTICE
*Description*::
This message occurs when enabling file system analytics on the volume fails because there is insufficient space in the volume. The enablement is allowed because the "-skip-space-validation" parameter is specified.
*Corrective Action*::
Increase the volume size or free up space on the volume. Use the "volume modify" command to increase volume size.
*Syslog Message*::
Enabling file system analytics on volume "%s" in SVM "%s" skips the space validation.
*Parameters*::
*volName* (STRING): Volume name.
*vserverName* (STRING): Name of the storage virtual machine (SVM) on which the volume resides.

== wafl.analytics.state.change
*Severity*::
NOTICE
*Description*::
This message occurs when the file system analytics state has been changed on a volume.
*Corrective Action*::
(None).
*Syslog Message*::
The file system analytics state of volume "%s%s" (DSID: "%lu") has changed to "%s". Reason: %s. Rulegen: %lu.
*Parameters*::
*volname* (STRING): Volume name.
*vserveruuid* (STRING): Universal Unique ID (UUID) of the volume's storage VM (SVM).
*dsid* (LONGINT): Unique identifier (DSID) of the volume.
*state* (STRING): File system analytics state: on or off.
*reason* (STRING): The reason that the file system analytics state was changed.
*rulegen* (LONGINT): File system analytics rules generation number.

== wafl.analytics.tooMuchMemory
*Severity*::
ALERT
*Description*::
This message occurs when the analytics subsystem has an excessive amount of pending work, causing memory usage to be higher than expected.
*Corrective Action*::
Contact Contact NetApp technical support. for assistance.
*Syslog Message*::
Reminder table size is "%lu", which is above the design limit of "%lu". System memory: "%lu". Time since last merge: "%lu".
*Parameters*::
*tablesize* (LONGINT): Current size of analytics subsystem reminder table.
*limit* (LONGINT): Design limit size of analytics subsystem reminder table.
*system_memory* (LONGINT): Total system memory on this node.
*last_merge* (LONGINT): Milliseconds since the analytics subsystem last processed a work request.

== wafl.analytics.tz.changed
*Severity*::
ERROR
*Description*::
This message occurs when the system timezone is changed while file system analytics is enabled on the node. As a consequence, file system analytics information might not accurately reflect the volume's content.
*Corrective Action*::
Use the "volume analytics show -state on" command to find the volumes with file system analytics enabled, then use the "volume analytics off" and "volume analytics on" commands for each volume where file system analytics is enabled.
*Syslog Message*::
The system timezone has been changed while file system analytics is enabled.
*Parameters*::
(None).

== wafl.analytics.updateDiscard
*Severity*::
ALERT
*Description*::
This message occurs when a file system analytics update is discarded. Instances of this message indicate low accuracy of the analytics data reported for the volume.
*Corrective Action*::
Turning file system analytics off and turning it back on again might resolve the issue. Find the name of the Vserver and volume using the "volume show -dsid <dsid>" command. Turn file system analytics off using the "volume analytics off" command, and then turn it back on by using the "volume analytics on" command. If the problem persists or further assistance is needed, contact NetApp technical support.
*Syslog Message*::
A file system analytics update was discarded due to an unexpected error. Analytics filehandle "%s" on the volume with DSID "%lu" was to be updated by file operation "%s".
*Parameters*::
*fh* (STRING): File handle that the operation targeted.
*dsid* (LONGINT): DSID of the volume affected by the discarded update.
*operation* (STRING): Operation that was being performed when this error occurred.
