---
sidebar: sidebar
permalink: wafl-inaccessible-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.inaccessible events
---

= wafl.inaccessible events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.inaccessible.userdata
*Severity*::
ERROR
*Description*::
This message occurs when an access request is received for inaccessible user data (area blocked by wafliron).
*Corrective Action*::
Use the "volume file show-inode" command with the file ID and volume name information to find the file path. Recover the file from a backup. For a SnapMirror(R) target, rebuild from the source or resynchronize. If the block is in a snapshot, delete the snapshot. Contact NetApp technical support for more options.
*Syslog Message*::
Inaccessible user data block at FBN %llu Level %u in %s inode (file ID:%s snapshot ID:%u file_type:%d disk_flags:0x%x) in volume %s%s%s%s.
*Parameters*::
*fbn* (LONGINT): File block number.
*level* (INT): Buffer level.
*file_space* (STRING): File space.
*fileid* (STRING): Identifying number for the suspect inode.
*snapid* (INT): Snapshot identifier: (0) - active file system (non-zero) - refers to snapshot
*type* (INT): File type.
*flags* (LONGINT): Inode disk flags.
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Uniquely identifies the volume in cases where the volume name itself is insufficient.
