---
sidebar: sidebar
permalink: wafl-zombie-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.zombie events
---

= wafl.zombie events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.zombie.susp.aggr.limit
*Severity*::
NOTICE
*Description*::
This message occurs when the aggregate encounters the zombie throttling limits during zombie delete processing for large number of file deletions.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL(R) aggregate %s is experiencing zombie throttling possibly due to requests for large number of file deletions. This can be mitigated by a combination of a) reducing the load on the aggregate or b) issuing the file deletion requests in smaller batches.
*Parameters*::
*aggrname* (STRING): Name of the aggregate.

== wafl.zombie.susp.vol.limit
*Severity*::
NOTICE
*Description*::
This message occurs when the volume encounters the zombie throttling limits during zombie delete processing for large number of file deletions.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL(R) volume %s%s%s%s is experiencing zombie throttling possibly due to requests for large number of file deletions. This can be mitigated by a combination of a) reducing the load on the volume or b) issuing the file deletion requests in smaller batches.
*Parameters*::
*volowner* (STRING): Owner of the volume.
*volname* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient. Consists of the Vserver name and UUID.
