---
sidebar: sidebar
permalink: wafl-gs-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.gs events
---

= wafl.gs events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.gs.metafile.load.failed
*Severity*::
ERROR
*Description*::
This message occurs when wafl is unsuccessful to check and load Granular Set metafile for the volume.
*Corrective Action*::
Issue volume offline followed by volume online and confirm this error message does not happen again. For more information or assistance, contact NetApp technical support.
*Syslog Message*::
Wafl failed to load metafile that stores wafl copy of SnapMirror CG.
*Parameters*::
*volume* (STRING): Volume name.
*error* (INT): Error code.

== wafl.gs.modify.op.failed
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL(R) prohibits loading a file for a modify operation on a read-only consistency group.
*Corrective Action*::
NONE.
*Syslog Message*::
Failed to load file ID %u on volume %s%s%s%s FSID:%u for a modify operation because it is part of a read-only sync relationship.
*Parameters*::
*fileid* (INT): File identifier.
*volowner* (STRING): Owner of the volume.
*volname* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient. Consists of the Vserver name and UUID.
*fsid* (INT): File system ID of the volume.

== wafl.gs.remove.rename.op.failed
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL(R) prohibits a rename operation or an unlink operation on a file part of a consistency group.
*Corrective Action*::
NONE.
*Syslog Message*::
Failed to load file ID %u on volume %s%s%s%s FSID:%u for a rename operation or an unlink operation because it is part of a sync relationship.
*Parameters*::
*fileid* (INT): File identifier.
*volowner* (STRING): Owner of the volume.
*volname* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient. Consists of the Vserver name and UUID.
*fsid* (INT): File system ID of the volume.

== wafl.gs.resync.gen.check.failed
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL(R) prohibits modification to a file that is part of a consistency group and the operation does not have the right generation enforcement parameters. This can occur if the operation happened before the SnapMirror(R) relationship was established.
*Corrective Action*::
NONE.
*Syslog Message*::
Unexpected operation on consistency group file ID %u on volume %s%s%s%s FSID:%u. This can occur if the operation happened before the SnapMirror relationship was established.
*Parameters*::
*fileid* (INT): File identifier.
*volowner* (STRING): Owner of the volume.
*volname* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient. Consists of the Vserver name and UUID.
*fsid* (INT): File system ID of the volume.
