---
sidebar: sidebar
permalink: wafl-vv-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.vv events
---

= wafl.vv events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.vv.bad.DSIDorMSID
*Severity*::
ERROR
*Description*::
This message occurs when Data ONTAP(R) cannot map a volume to serve a client request because of invalid data Set Identifiers. Protocol access to the volume is disabled.
*Corrective Action*::
Take the volume offline and contact NetApp technical support.
*Syslog Message*::
Cannot map volume '%s%s%s' to serve client requests because of invalid data set identifiers.
*Parameters*::
*vol* (STRING): Volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.vv.clone.splitBusySnap
*Severity*::
NOTICE
*Description*::
This event is to inform the user that a volume clone cannot split from its parent volume due to busy snapshots.
*Corrective Action*::
Determine which snapshots in the clone volume are busy and correct the condition that is causing them to be busy. Then, retry the operation.
*Syslog Message*::
Volume '%s%s%s' has locked snapshots, not splitting.
*Parameters*::
*vol* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.vv.clone.splitNoScan
*Severity*::
NOTICE
*Description*::
This event is to inform user that the system is unable to start a volume clone scanner, so the clone volume will not be split from its parent volume.
*Corrective Action*::
This may be a temporary issue. Please retry the volume clone split operation after sometime.
*Syslog Message*::
Unable to start clone split scanner on volume '%s%s%s'.
*Parameters*::
*vol* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.vv.dup.DSID2
*Severity*::
ERROR
*Description*::
This message occurs when another volume is already registered with the data set identifier (DSID) assigned to this volume.
*Corrective Action*::
Contact NetApp technical support.
*Syslog Message*::
Duplicate volume '%s%s%s' DSID (%08x) detected in aggregate '%s'.
*Parameters*::
*vol* (STRING): Volume name.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where the volume name itself is insufficient.
*dsid* (LONGINT): Data set identifier.
*aggr* (STRING): Aggregate name.

== wafl.vv.dup.UUID
*Severity*::
NOTICE
*Description*::
This message occurs when the system detects and updates a duplicate volume Universally Unique Identifier (UUID).
*Corrective Action*::
(None).
*Syslog Message*::
vvol '%s' in aggregate '%s' duplicate UUID %s was changed to %s.
*Parameters*::
*vol* (STRING): Volume name.
*aggr* (STRING): Aggregate name.
*old_uuid* (STRING): Old duplicated UUID for the volume.
*new_uuid* (STRING): Replacement UUID for the volume.

== wafl.vv.raidfile.open
*Severity*::
NOTICE
*Description*::
This event is to inform user that the system can not open the raid label file for update and the reason.
*Corrective Action*::
(None).
*Syslog Message*::
Unable to open volume descriptor: %s
*Parameters*::
*err* (STRING): The error message

== wafl.vv.raidfile.readOnly
*Severity*::
NOTICE
*Description*::
This event is to inform user that the raid label file can not be updated on a read only volume.
*Corrective Action*::
(None).
*Syslog Message*::
Unable to update volume descriptor, aggregate '%s' is readonly
*Parameters*::
*vol* (STRING): The volume name

== wafl.vv.raidfile.update
*Severity*::
NOTICE
*Description*::
This event is to inform user that while renaming a virtual volume, the system is unable to update the volume's raid label file
*Corrective Action*::
(None).
*Syslog Message*::
%s: Can't rewrite descriptor for volume '%s%s%s', aggregate '%s', error code %d.
*Parameters*::
*cmd* (STRING): The command name
*vol* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.
*aggr* (STRING): The aggregate name
*err* (INT): The error code

== wafl.vv.regen.instance.uuid
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when the instance UUID and the provenance UUID of a FlexVol(tm) volume have been regenerated.
*Corrective Action*::
(None).
*Syslog Message*::
For FlexVol volume '%s' with FSID 0x%x and instance UUID %s, a new instance UUID and provenance UUID (both being %s) have been generated.
*Parameters*::
*vol* (STRING): Volume name.
*fsid* (INT): File system identifier.
*oldinstuuid* (STRING): Old instance UUID of the volume.
*instuuid* (STRING): New instance UUID of the volume. This is also the new prevenance UUID.

== wafl.vv.rename.dup
*Severity*::
NOTICE
*Description*::
This message occurs when a duplicate flexible volume name is changed to a unique name.
*Corrective Action*::
(None).
*Syslog Message*::
Duplicate flexible volume name '%s%s%s' changed to '%s%s%s' in aggregate '%s'.
*Parameters*::
*oldname* (STRING): Duplicate name.
*app* (STRING): Application UUID.
*volident1* (STRING): If the volume belongs to a vserver, this is that vserver's Universal Unique Identifier (UUID).
*newname* (STRING): New name.
*app2* (STRING): Application UUID.
*volident2* (STRING): If the volume belongs to a vserver, this is that vserver's Universal Unique Identifier (UUID).
*aggrname* (STRING): Name of the containing aggregate.

== wafl.vv.set.size
*Severity*::
NOTICE
*Description*::
This event is issued when setting virtual volume size to the size indicated in fsinfo
*Corrective Action*::
(None).
*Syslog Message*::
Setting volume size for %s%s%s%s to match nominal size.
*Parameters*::
*owner* (STRING): The volume owner
*name* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.vv.softlocks.noParent
*Severity*::
NOTICE
*Description*::
This event is to inform user that to remove softlocks associated with a volume clone, the parent volume must be online
*Corrective Action*::
(None).
*Syslog Message*::
Unable to find parent volume when destroying clone '%s%s%s' softlocks. Ensure the parent volume is online then retry the operation.
*Parameters*::
*vol* (STRING): The volume name
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.vv.vol.config
*Severity*::
NOTICE
*Description*::
This event is issued to inform the user that the system can not configure a virtual volume and the reason.
*Corrective Action*::
(None).
*Syslog Message*::
Unable to configure volume in aggregate '%s': %s
*Parameters*::
*vol* (STRING): The volume name
*err* (STRING): The error string

== wafl.vv.vol.maxvols
*Severity*::
NOTICE
*Description*::
This message occurs when the system cannot configure a FlexVol(R) volume because the maximum number of volumes has been reached.
*Corrective Action*::
Destroy some existing volumes to make room for new ones.
*Syslog Message*::
Cannot configure FlexVol volume '%s' (UUID %s) in aggregate '%s': There are too many FlexVol volumes (%d) on the system. The limit for %s is %d.
*Parameters*::
*vol* (STRING): FlexVol name.
*uuid* (STRING): FlexVol unique ID.
*aggregate* (STRING): Aggregate name.
*count* (INT): Current number of FlexVol volumes.
*model* (STRING): System model name.
*limit* (INT): Limit for the number of FlexVol volumes.
