---
sidebar: sidebar
permalink: wafl-repl-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.repl events
---

= wafl.repl events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.repl.badTimestamp
*Severity*::
NOTICE
*Description*::
This message occurs when a replication operation receives a timestamp with an invalid nanoseconds portion, and clears it.
*Corrective Action*::
(None).
*Syslog Message*::
Encountered invalid %s time on inode %u of volume %u.
*Parameters*::
*type* (STRING): Type of timestamp.
*inode_num* (INT): Identifier of the affected file.
*fsid* (INT): Identifier of the volume.

== wafl.repl.maxdirsize.notice
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL(R) sets the maximum directory size of a SnapMirror(R) destination volume to a value higher than its default during a SnapMirror transfer.
*Corrective Action*::
(None).
*Syslog Message*::
The maxdirsize (%u KB) of volume %s (FSID %u) is higher than the default (%u KB). There might be a performance penalty when doing operations on large directories. This was generated for a SnapMirror relationship with ID %s.
*Parameters*::
*current_maxdirsize* (INT): Current maximum directory size value.
*vol* (STRING): Name of the volume.
*volFsid* (INT): File system ID (FSID) of the volume.
*default_maxdirsize* (INT): Default maximum directory size value.
*SnapMirrorID* (STRING): Unique ID of the SnapMirror relationship for this operation, which can be used to match this message with messages for the same relationship in other logs (for example, the SnapMirror log at /mroot/etc/log/snapmirror_audit).

== wafl.repl.raid.incons.set.error
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when Replication propagates RAID error from the source and marks an on-disk data block on the destination with the same error as the source. This is useful for tracking pseudo bad and unverified blocks error propagation.
*Corrective Action*::
Contact NetApp technical support.
*Syslog Message*::
Data block in %s inode (fileid: %u snapid: %u fbn: %llu level: %u) in volume %s%s%s%s marked with error (%u) by %s as a result of Raid Error Propagation from Source. Block previously had error (%u).
*Parameters*::
*inotype* (STRING): Inode space (public or private).
*fileid* (INT): Identifying number for the inode.
*snapid* (INT): Snapshot identifier: (0) - active file system (non-zero) - refers to snapshot
*fbn* (LONGINT): File block number.
*level* (INT): Buffer level.
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Uniquely identifies the volume when the volume name itself is insufficient.
*error* (INT): Error on the block.
*module* (STRING): Module that is marking the block with the error.
*prev_error* (INT): Previous error on the block.

== wafl.repl.src.inconsistent
*Severity*::
ERROR
*Description*::
This message occurs when the replication source engine encounters a disk error in the file system metadata. Replication transfer will abort.
*Corrective Action*::
Run wafliron to fix the active file system. To continue replication transfer, delete the snapshots containing this bad block.
*Syslog Message*::
%s: %s%s%s%s: WAFL metadata inconsistent due to disk errors. (vvbn:%u level:%u file_type:%d). Aborting transfer.
*Parameters*::
*vol_type* (STRING): Whether the block was being accessed for a volume or an aggregate.
*owner* (STRING): String indicating the owner of the affected volume or aggregate.
*vol* (STRING): Name of the volume or aggregate.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases where the volume name itself is insufficient.
*vvbn* (INT): Virtual Volume Block Number.
*level* (INT): Buffer level.
*file_type* (INT): File type.

== wafl.repl.zombie.scan.susp
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when a logical break zombie restart is going through a scan of composite zombies and it suspends the incoming client composite delete requests.
*Corrective Action*::
(None).
*Syslog Message*::
The deletion of file with fileid %d is suspended because volume %s (FSID %u) is going through a logical break. The file delete will be resumed after logical break is complete.
*Parameters*::
*fileid* (INT): File identifier.
*vol* (STRING): Name of the volume.
*volFsid* (INT): File system ID (FSID) of the volume.
