---
sidebar: sidebar
permalink: wafl-readdir-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.readdir events
---

= wafl.readdir events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.readdir.expired
*Severity*::
ERROR
*Description*::
This message occurs when a READDIR file operation has exceeded the timeout that it is allowed to run in WAFL. This can be the result of very large or sparse directories, and corrective action is recommended.
*Corrective Action*::
You can find information specific to recent directories that have had READDIR file operations expire by using the 'diag' privilege nodeshell CLI command: "wafl readdir notice show" If a directory is indicated as sparse, it is recommended that you copy the contents of the directory to a new directory to remove the sparseness of the directory file. If a directory is not indicated as sparse and the directory is large, it is recommended that you reduce the size of the directory file by reducing the number of file entries in the directory.
*Syslog Message*::
A READDIR file operation has expired for the directory associated with volume "%s%s/%s" snapshot ID %d and inode %d.
*Parameters*::
*volume* (STRING): Volume name that the directory is in.
*app* (STRING): Application universal unique identifier (UUID).
*volident* (STRING): Volume identifier to uniquely identify the volume in cases where the volume name alone is insufficient.
*snapid* (LONGINT): Snapshot ID that the directory is in.
*directory_inum* (LONGINT): The inode number (file ID) of the directory.
*object_uuid* (STRING): Volume instance UUID of the resource object.

== wafl.readdir.sparse
*Severity*::
NOTICE
*Description*::
This message occurs when a READDIR file operation detects that a directory is sparse while iterating over its directory entries. Iterating over sparse directories could negatively impact performance on the node.
*Corrective Action*::
You can find information specific to directories that have had READDIR file operations detect a sparse directory by using the 'diag' privilege nodeshell CLI command: "wafl readdir notice show" It is recommended that you copy the contents of the directory to a new directory to remove the sparseness of the directory file.
*Syslog Message*::
A READDIR file operation has detected that a directory associated with volume %s%s/%s snapshot ID %d and inode %d is sparse.
*Parameters*::
*volume* (STRING): Volume name that the directory is in.
*app* (STRING): Application UUID.
*volident* (STRING): Volume identifier to uniquely identify the volume in cases where the volume name alone is insufficient.
*snapid* (LONGINT): Snapshot ID the that the directory is in.
*directory_inum* (LONGINT): The inode number (fileid) of the directory.
