---
sidebar: sidebar
permalink: wafl-snapshot-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.snapshot events
---

= wafl.snapshot events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.snapshot.badFilesize
*Severity*::
NOTICE
*Description*::
This event is issued when the system discover that a filesize is out of range in a snapshot.
*Corrective Action*::
(None).
*Syslog Message*::
File size out of range in snapshot.
*Parameters*::
(None).

== wafl.snapshot.badLevel
*Severity*::
NOTICE
*Description*::
This event is issued when there is an inconsistency in the metadata of an inode in a snapshot. This message is advisory only. The inconsistency will be corrected in memory only, and the data will be made available.
*Corrective Action*::
No action is required; however, the message may repeat until the snapshot is deleted.
*Syslog Message*::
Corrected bad level %d for buftree of %s fileid %d, snapid %d in %s %s%s%s%s
*Parameters*::
*level* (INT): The level of the buftree of the file
*ino_type* (STRING): The inode type
*fileid* (INT): The file identifier
*snapid* (INT): The snapshot identifier
*type* (STRING): The type of object (volume/aggregate)
*owner* (STRING): The owner of the volume
*vol* (STRING): The name of the volume
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.

== wafl.snapshot.ecv.fail
*Severity*::
ERROR
*Description*::
This message occurs when the system attempts to create a snapshot on a mixed-version cluster. However, the effective version of the cluster is ONTAP(R) 9.3 or earlier, and the maximum number of snapshots supported by this effective version has already been reached.
*Corrective Action*::
Upgrade all nodes in the cluster to ONTAP 9.4 or later.
*Syslog Message*::
Snapshot create operation failed on volume %s%s%s. Maximum number of snapshots reached on a mixed-version cluster.
*Parameters*::
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): ID of the volume.
