---
sidebar: sidebar
permalink: wafl-snapshot_xlation_duplicate_entry-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.snapshot_xlation_duplicate_entry events
---

= wafl.snapshot_xlation_duplicate_entry events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.snapshot_xlation_duplicate_entry
*Severity*::
ALERT
*Description*::
This message occurs when WAFL(R) determines that there are duplicate snapshot entries in the snapshot translation table. Access to this snapshot is disabled until the problem is resolved.
*Corrective Action*::
The snapshot is inaccessible because the corresponding entry in the translation table has been cleared. Contact NetApp technical support resolve the problem.
*Syslog Message*::
WAFL snapshot translation table: Duplicate entry for volume '%s%s%s' that maps physical snapshot '%d' to logical snapshot '%d'.
*Parameters*::
*owner* (STRING): Owner of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases where the volume name itself is insufficient.
*physical_snapid* (INT): Physical snapshot index.
*Logical_snapid* (INT): Logical snapshot index.
