---
sidebar: sidebar
permalink: wafl-s2c-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.s2c events
---

= wafl.s2c events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.s2c.snap.check.failed
*Severity*::
ERROR
*Description*::
This message occurs when SnapMirror(R) logical transfer is not possible due to incompatible snapshot.
*Corrective Action*::
Create new snapshot on the source volume and use that for Logical transfer.
*Syslog Message*::
SnapMirror operation failed in volume '%s%s%s' for snapshot ID %d because %s.
*Parameters*::
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases where the volume name itself is insufficient.
*snapId* (INT): Identifier for the snapshot.
*reason* (STRING): Specific reason for failure.

== wafl.s2c.snap.lang.mismatch
*Severity*::
ERROR
*Description*::
This message occurs when SnapMirror(R) restore cannot proceed due to language mismatch at source and destination end.
*Corrective Action*::
Create new volume with correct language settings.
*Syslog Message*::
SnapMirror operation failed in %s because of language mismatch between source and destination.Language at destination: '%s'. Language at source: '%s'.
*Parameters*::
*vol* (STRING): Name of the volume.
*src_lang_setting* (STRING): Language setting at source.
*dest_lang_setting* (STRING): Language setting at destination.
