---
sidebar: sidebar
permalink: wafl-shutdown-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.shutdown events
---

= wafl.shutdown events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.shutdown.notClean
*Severity*::
NOTICE
*Description*::
This message occurs during shutdown, to indicate that a volume has not been marked clean. By itself, this is not necessarily a problem. When this event occurs in conjunction with WAFL inconsistency panics or higher-severity EMS events, this message can indicate a potential source of the inconsistencies.
*Corrective Action*::
No immediate action is required. If this message occurs in conjunction with WAFL inconsistency panics or other EMS messages, contact NetApp technical support.
*Syslog Message*::
%s %s%s%s%s not marked clean (volume state is %s).
*Parameters*::
*type* (STRING): Type of object (volume/aggregate).
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume when the volume name by itself is insufficient.
*state* (STRING): State of the volume.
