---
sidebar: sidebar
permalink: wafl-32bit-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.32bit events
---

= wafl.32bit events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.32bit.formatUnsupported
*Severity*::
ERROR
*Description*::
This message occurs when an aggregate or volume with a 32-bit or mixed format file system is found. These formats are unsupported in this version of Data ONTAP(R), and the volume cannot be brought online.
*Corrective Action*::
Contact NetApp technical support.
*Syslog Message*::
%s %s%s%s%s has an unsupported 32-bit or mixed format file system (snapshot ID %u).
*Parameters*::
*type* (STRING): Type of object (volume or aggregate).
*owner* (STRING): Volume owner.
*vol* (STRING): Volume name.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases where the volume name itself is insufficient.
*snapid* (INT): Snapshot identifier: (0) - active file system (non-zero) - refers to snapshot
