---
sidebar: sidebar
permalink: wafl-bagofbits-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.bagofbits events
---

= wafl.bagofbits events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.bagofbits.name
*Severity*::
ERROR
*Description*::
This message occurs when a read directory request from an NFSv4 client is made to a Unicode-based directory in which directory entries with no NFS alternate name contain non-Unicode characters.
*Corrective Action*::
Use the "volume file show-inode" command with the file ID and volume name information to find the file path. Access the parent directory from an NFSv3 client and rename the entry using Unicode characters.
*Syslog Message*::
Cannot provide directory entry to NFSv4 client for file ID:%d in volume %s%s because it contains non-Unicode characters with no NFS alternate name.
*Parameters*::
*fileid* (INT): File ID of the entry in the directory for which non-Unicode characters are present.
*vol* (STRING): Volume in which the directory entry with non-unicode characters is present.
*app* (STRING): Application UUID.
*volident* (STRING): Unique volume identifier (UUID) when the volume name itself is insufficient.
