---
sidebar: sidebar
permalink: wafl-slice-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.slice events
---

= wafl.slice events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.slice.invalid.stream
*Severity*::
NOTICE
*Description*::
This message occurs when an invalid slice stream was not fixed by wafliron because the associated slice base file was not recognized at the time wafliron ran. Once this invalid stream file is removed, 'wafl slice_repair' can recreate and repair the stream file.
*Corrective Action*::
A slice stream file in the slicevol is not valid. Please remove the file and rerun 'wafl slice_repair' to create a valid slice stream file - Use the (privilege :diag) "rm -x [stream_file_name] [slice_base_path]" command to remove the invalid slice stream file in the slicevol. Then use the (privilege:diag) "wafl slice_repair[slice_base_path] start" command to repair the stream file. If the problem persists, contact NetApp technical support.
*Syslog Message*::
Invalid slice stream file: %s (fileid %d) in the slice base path %s in volume %s%s%s detected. Please run the following commands in the diag mode: %s to fix it.
*Parameters*::
*stream_name* (STRING): The name of an invalid slice stream file.
*stream_fileid* (INT): The file ID of an invalid slice stream file.
*base_path* (STRING): The slice base file path that is being repaired.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Vserver's Universal Unique Identifier (UUID).
*repair_cmd* (STRING): The repair command to restore the stream file to be valid.
