---
sidebar: sidebar
permalink: wafl-offline-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.offline events
---

= wafl.offline events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.offline.infoError
*Severity*::
ALERT
*Description*::
This message occurs when the system attempts to place a volume online, but cannot read the volinfo or fsinfo data for the volume.
*Corrective Action*::
Volume is inconsistent. Contact NetApp technical support.
*Syslog Message*::
Either both volinfo blocks or fsinfo block on %s %s%s%s%s are/is invalid.
*Parameters*::
*type* (STRING): Type of object (volume or aggregate).
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier for the volume, for cases when the volume name is insufficient.

== wafl.offline.openfiles
*Severity*::
NOTICE
*Description*::
This message occurs when wafliron detects a failure while trying to perform an operation because files are open.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
'%s %s' might not be '%s%s' because of '%u' open file'%s'.
*Parameters*::
*voltype* (STRING): Aggregate.
*volname* (STRING): Volume name.
*operation* (STRING): Operation.
*suffix* (STRING): Suffix.
*uses* (INT): Number of open files.
*plural* (STRING): Plural.

== wafl.offline.proc.file
*Severity*::
NOTICE
*Description*::
This message occurs when wafliron detects a failure while trying to perform an operation because a process has open files.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
The '%s' process has '%u' file'%s' open.
*Parameters*::
*procname* (STRING): Process name.
*openfiles* (INT): Number of open files.
*plural* (STRING): Plural.

== wafl.offline.proc.file.unres
*Severity*::
NOTICE
*Description*::
This message occurs when wafliron detects a failure while trying to perform an operation because a process has unresolved open files.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
Could not resolve '%u' of '%s's' open file names.
*Parameters*::
*openfiles* (INT): Number of open files.
*procname* (STRING): Process name.

== wafl.offline.quiesce.aborted
*Severity*::
NOTICE
*Description*::
This message occurs when wafliron detects a failure while waiting for a volume reference lock to be taken.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
The wait for uses of '%s %s' to quiesce was aborted.
*Parameters*::
*voltype* (STRING): Aggregate.
*aggrname* (STRING): Aggregate name.

== wafl.offline.quiesced
*Severity*::
NOTICE
*Description*::
This message occurs when wafliron detects a success while waiting for a volume reference lock to be taken.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
Uses of '%s %s' preventing '%s' have quiesced.
*Parameters*::
*voltype* (STRING): Aggregate.
*aggrname* (STRING): Aggregate name.
*operation* (STRING): Operation.

== wafl.offline.versionMismatch
*Severity*::
EMERGENCY
*Description*::
This message occurs when the system is inspecting an offline volume by reading the super block and discovers that there is a version mismatch.
*Corrective Action*::
Confirm that the correct Data ONTAP(R) version is in use; if not, reboot or upgrade to the correct version as necessary. For more information or assistance, contact NetApp technical support.
*Syslog Message*::
This version of Data ONTAP does not recognize the filesystem of offline %s %s%s%s%s. The volume is probably from a later version of the software.
*Parameters*::
*type* (STRING): Type of object (volume/aggregate).
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Unique identifier of the volume in cases in which the volume name itself is insufficient.

== wafl.offline.volref.msg
*Severity*::
NOTICE
*Description*::
This message indicates the volume reference message that prevents the operation on an aggregate.
*Corrective Action*::
No corrective action is required for this notification event.
*Syslog Message*::
'%s' prevents '%s' of '%s %s'.
*Parameters*::
*volreftext* (STRING): Volume reference message text.
*operation* (STRING): Operation.
*voltype* (STRING): Aggregate.
*aggrname* (STRING): Aggregate name.
