---
sidebar: sidebar
permalink: wafl-compress-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.compress events
---

= wafl.compress events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== wafl.compress.auto.disable
*Severity*::
NOTICE
*Description*::
This message occurs when compression is automatically disabled on a space guarantee volume because it is not supported on this platform.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL compression automatically disabled in %s "%s".
*Parameters*::
*volume_identifier* (STRING): Volume identifier.
*volume* (STRING): Volume name.

== wafl.compress.cde.auto.enablement
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL compression on container file level is automatically enabled on a volume.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL auto adaptive compression automatically enabled in %s "%s".
*Parameters*::
*volume_identifier* (STRING): Volume identifier.
*volume* (STRING): Volume name.

== wafl.compress.cde.event
*Severity*::
NOTICE
*Description*::
This message occurs when WAFL compression on container file level is enabled or disabled on a volume.
*Corrective Action*::
(None).
*Syslog Message*::
WAFL container compression state changed in %s "%s" to "%s".
*Parameters*::
*volume_identifier* (STRING): Volume identifier.
*volume* (STRING): Volume name.
*message* (STRING): Whether enable or disable.

== wafl.compress.enable.failed
*Severity*::
INFORMATIONAL
*Description*::
This event is issued when FAS compression can not be enabled on a volume. The following reasons might be causing the problem: FAS compression might not be supported on the software release you're running; the volume is not a flexible volume or it is a root volume or snaplock volume; the compression/de-compression scanner is already active; or a clone operation is already underway.
*Corrective Action*::
(None).
*Syslog Message*::
Compression could not be enabled on volume "%s" at this time. Check the volume configuration and retry.
*Parameters*::
*vol* (STRING): Volume name.

== wafl.compress.fail.rootVol
*Severity*::
NOTICE
*Description*::
This message occurs when an administrator attempts to enable compression on the root volume. Compression cannot be enabled on the root volume.
*Corrective Action*::
(None).
*Syslog Message*::
'%s' is the root volume and compression cannot be enabled on the root volume.
*Parameters*::
*vol* (STRING): Volume name.

== wafl.compress.mark.cg.bad.hw
*Severity*::
ALERT
*Description*::
This message occurs when the FAS compression writes bad blocks for an inconsistent or corrupted compression group due to hardware errors.
*Corrective Action*::
Restore the corrupted file from the snapshot, or contact NetApp technical support
*Syslog Message*::
FAS compression: Writing bad blocks, at fbn:%llu level:%u in %s inode (fileid:%d snapid:%u) in volume %s%s%s%s.
*Parameters*::
*fbn* (LONGINT): File block number.
*level* (INT): Buffer level.
*ino_type* (STRING): Inode type
*fileid* (INT): Identifying number for the suspect inode.
*snapid* (INT): Snapshot identifier: (0) - active file system (non-zero) - refers to snapshot
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Uniquely identifies the volume in cases where the volume name itself is insufficient.

== wafl.compress.mark.cg.bad.sw
*Severity*::
ERROR
*Description*::
This message occurs when the FAS compression writes bad blocks for an inconsistent or corrupted compression group due to software errors.
*Corrective Action*::
Restore the corrupted file from the snapshot, or contact NetApp technical support
*Syslog Message*::
FAS compression: Writing bad blocks, at fbn:%llu level:%u in %s inode (fileid:%d snapid:%u) in volume %s%s%s%s.
*Parameters*::
*fbn* (LONGINT): File block number.
*level* (INT): Buffer level.
*ino_type* (STRING): Inode type
*fileid* (INT): Identifying number for the suspect inode.
*snapid* (INT): Snapshot identifier: (0) - active file system (non-zero) - refers to snapshot
*owner* (STRING): Owner of the volume.
*vol* (STRING): Name of the volume.
*app* (STRING): Application UUID.
*volident* (STRING): Uniquely identifies the volume in cases where the volume name itself is insufficient.

== wafl.compress.scan.checkpoint.deleted
*Severity*::
NOTICE
*Description*::
This event is generated when the FAS compression of existing data for volume deletes checkpoint.
*Corrective Action*::
(None).
*Syslog Message*::
vol compress: Checkpoint deleted for compression of existing data for volume "%s%s%s".
*Parameters*::
*vol* (STRING): Name of the compressed volume.
*app* (STRING): Application UUID.
*volident* (STRING): To uniquely identify the volume in cases where volume name itself is insufficient.
